AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Monorepo for API and Scheduled Lambda Functions

Resources:
  ApiFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: api_function.main.handler
      Runtime: python3.13
      CodeUri: .
      Timeout: 10
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /data
            Method: get

  # ScheduledFunction:
  #   Type: AWS::Serverless::Function
  #   Properties:
  #     Handler: scheduled_function.main.handler
  #     Runtime: python3.13
  #     CodeUri: .
  #     Timeout: 10
  #     Events:
  #       ScheduledEvent:
  #         Type: Schedule
  #         Properties:
  #           Schedule: rate(1 hour)
