AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Monorepo for API and Scheduled Lambda Functions

Resources:
  ApiFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: main.handler
      Runtime: python3.13
      CodeUri: ./api_function
      Timeout: 10
      FunctionUrlConfig:
        AuthType: NONE    
  CollectDataFunction:
     Type: AWS::Serverless::Function
     Properties:
       Handler: main.handler
       Runtime: python3.13
       CodeUri: ./collect_data_function
       Timeout: 300        