name: Deploy to AWS

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  test:
    name: "Run Tests"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2

      - name: Install python
        uses: actions/setup-python@v5.4.0
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          cd api_function
          pip install -r requirements.txt
          cd ..
          cd collect_data_function
          pip install -r requirements.txt
          cd ..

      - name: Set fake AWS credentials
        run: |
          echo "AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}" >> $GITHUB_ENV
          echo "AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> $GITHUB_ENV
          echo "AWS_REGION=${{ secrets.AWS_REGION }}" >> $GITHUB_ENV
          echo "TEST_ENV=True" >> $GITHUB_ENV

      - name: Run tests
        run: |
          pytest tests/ --disable-warnings
  deploy:
    name: "Deploy to AWS"
    needs: test
    runs-on: ubuntu-latest
    environment: DEV

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2

      - name: Installing the AWS CLI
        run: |
          sudo apt-get update -y
          sudo apt-get install -y unzip
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip awscliv2.zip
          sudo ./aws/install --update

      - name: Add AWS CLI to PATH
        run: |
          echo "Adding AWS CLI to PATH"
          echo "/usr/local/bin" >> $GITHUB_PATH

      - name: Verify AWS CLI
        run: |
          echo "Checking AWS CLI version..."
          aws --version || echo "AWS CLI is not installed correctly!"

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Installing the AWS SAM CLI
        run: |
          curl -Lo aws-sam-cli-linux.zip https://github.com/aws/aws-sam-cli/releases/latest/download/aws-sam-cli-linux-x86_64.zip
          unzip aws-sam-cli-linux.zip -d sam-installation
          sudo ./sam-installation/install --update

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          cd api_function
          pip install -r requirements.txt
          cd ..
          cd collect_data_function
          pip install -r requirements.txt
          cd ..

      - name: Building a SAM package
        run: sam build

      - name: Deploy AWS Lambda via SAM
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
        run: sam deploy --stack-name my-lambda-stack
