name: Deploy to AWS

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  test:
    name: "Run Tests"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2

      - name: Install python
        uses: actions/setup-python@v5.4.0
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          cd api_function
          pip install -r requirements.txt
          cd ..
          cd collect_data_function
          pip install -r requirements.txt
          cd ..

      - name: Set fake AWS credentials
        run: |
          echo "AWS_ACCESS_KEY_ID=fakeaccesskey" >> $GITHUB_ENV
          echo "AWS_SECRET_ACCESS_KEY=fakesecretkey" >> $GITHUB_ENV
          echo "AWS_DEFAULT_REGION=us-east-1" >> $GITHUB_ENV

      - name: Run tests
        run: |
          pytest tests/ --disable-warnings
